name: voice_control
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_background_service: ^2.4.6
  flutter_background_service_android:
  flutter_background_service_ios:
  permission_handler: ^10.2.0
  flutter_local_notifications: ^14.0.0+1
  installed_apps: ^1.3.1
  external_app_launcher: ^3.1.0
  speech_to_text: ^6.1.1
  vosk_flutter: ^0.3.48
  device_apps: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/models/
